eggjs/cluster

- lib/master.js
- package.json
- test/app_worker.test.js
- test/fixtures/apps/app-kill/app/router.js
- test/fixtures/apps/app-kill/config/config.default.js
- test/fixtures/apps/app-kill/package.json
- vscode debug 的时候, 指定 port 为 worker
- 当 vscode 终止 debug 时, 只会 SIGKILL worker, 导致 agent 还在占用
- 故开发模式 && debug 模式下, 如果 worker 被 kill, master 也主动 exit
> feat: when debug mode, master should exit when worker die

- package.json
> feat: npm publish files limit

- .travis.yml
- appveyor.yml
- package.json
- test/fixtures/apps/agent-debug-port/agent.js
- test/fixtures/apps/agent-debug-port/package.json
- test/master.test.js
> test: add test for agent debug port

- lib/agent_worker.js
- lib/app_worker.js
- test/agent_worker.test.js
- test/app_worker.test.js
- test/fixtures/apps/agent-start-error/agent.js
- test/fixtures/apps/agent-start-error/package.json
- test/fixtures/apps/app-error-listeners/app.js
- test/fixtures/apps/app-error-listeners/app/router.js
- test/fixtures/apps/app-error-listeners/config/config.default.js
- test/fixtures/apps/app-error-listeners/package.json
- test/fixtures/apps/app-start-error/app.js
- test/fixtures/apps/app-start-error/package.json
> feat: exit when error emitted during start

- lib/utils/options.js
- package.json
- test/fixtures/apps/app-server/config/config.default.js
- test/fixtures/apps/cluster_mod_app/config/config.default.js
- test/fixtures/apps/cluster_mod_sticky/config/config.default.js
- test/fixtures/apps/frameworkapp/config/config.default.js
- test/options.test.js
> feat: use egg-utils

- lib/agent_worker.js
- test/agent_worker.test.js
Close https://github.com/eggjs/egg/issues/612
> fix: should print logger when agent start error

- lib/app_worker.js
> fix: start error should log what happend

- lib/agent_worker.js
- lib/app_worker.js
> fix: fix typo

- .travis.yml
- appveyor.yml
- lib/master.js
- package.json
- test/app_worker.test.js
- test/master.test.js
> feat: reduce info logs on local env

- package.json
- test/agent_worker.test.js
> test: sleep 20s to wait for agent process start

- lib/agent_worker.js
- lib/app_worker.js
- package.json
see https://github.com/eggjs/egg-cluster/pull/27
> feat: use graceful-process to refactor app and agent worker

- appveyor.yml
- lib/agent_worker.js
- lib/app_worker.js
- lib/utils/console.js
- test/master.test.js
> refactor: set agent worker and app worker console level

- test/agent_worker.test.js
- test/app_worker.test.js
- test/master.test.js
> refactor: disable console

- test/app_worker.test.js
- test/fixtures/apps/app-listen-without-port/config/config.default.js
> test: fix test that should mock the default port

- lib/master.js
https://github.com/eggjs/egg-cluster/pull/34#discussion_r129213455
> fix: debug status detect should support inspect

- lib/utils/options.js
- test/master.test.js
- test/options.test.js
https://github.com/eggjs/egg-cluster/pull/41/commits/ab298dea5730f78496d8ffa6689c485d86a98da3#r137325709
> fix: options.debugProtocol && options.debugAgent

- lib/app_worker.js
- lib/master.js
- test/master.test.js
> feat: agent debugPort 5856 -> 5800

- lib/master.js
- test/fixtures/apps/egg-ready/agent.js
- test/fixtures/apps/egg-ready/app.js
- test/fixtures/apps/egg-ready/app/router.js
- test/fixtures/apps/egg-ready/config/config.default.js
- test/master.test.js
> fix: should send egg-ready when app/agent restarted after launched

- lib/master.js
- package.json
> fix: should disable worker refork

- test/app_worker.test.js
> test: `don't fork` has been printed to stdout

- lib/master.js
- test/master.test.js
> fix: should send current worker pids when agent restart

- lib/master.js
> chore: log runtime versions

- README.md
- lib/app_worker.js
- lib/utils/options.js
- package.json
- test/master.test.js
- test/options.test.js
- add `options.httpsOptions`
- https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options
- close https://github.com/eggjs/egg/issues/1870
> feat: https options

- lib/master.js
- test/fixtures/apps/check-status/app.js
- test/master.test.js
https://github.com/eggjs/egg/issues/2633
我觉得可以直接在 local 下，就不启用检查，所以就按照这么改，看一下合不合适？
> feat: not start check in local

- lib/master.js
- test/agent_worker.test.js
- test/fixtures/apps/agent-debug-port/app.js
- test/fixtures/apps/agent-debug-port/package.json
添加agentDebugPort参数，方便同时使用vscode 调试两个egg项目
> support config agent debug port

- .travis.yml
- lib/master.js
> feat: replace worker file from outside

- lib/master.js
- lib/utils/terminate.js
- package.json
- test/fixtures/apps/sub-process-sigkill/app.js
- test/fixtures/apps/sub-process-sigkill/package.json
- test/fixtures/apps/sub-process-sigkill/worker1.js
- test/fixtures/apps/sub-process-sigkill/worker2.js
- test/fixtures/apps/sub-process/app.js
- test/fixtures/apps/sub-process/package.json
- test/fixtures/apps/sub-process/worker1.js
- test/fixtures/apps/sub-process/worker2.js
- test/master.test.js
> feat: kill all sub processes when exit

- lib/agent_worker.js
- test/agent_worker.test.js
- test/fixtures/apps/agent-die-onboot/app.js
fix https://github.com/eggjs/egg/issues/3099
> fix: should not start app when agent start fail

- README.md
Remove `options.typescript`, it has deprecated.
> docs: remove `options.typescript`

- README.md
- lib/master.js
- test/master.test.js
close https://github.com/eggjs/egg/issues/3511
> feat: save pid file

- .travis.yml
- appveyor.yml
- lib/agent_worker.js
- lib/app_worker.js
- lib/master.js
- package.json
- test/agent_worker.test.js
- test/app_worker.test.js
- test/fixtures/apps/agent-start-framework-error/agent.js
- test/fixtures/apps/agent-start-framework-error/package.json
- test/fixtures/apps/agent-start-framework-ready-error/agent.js
- test/fixtures/apps/agent-start-framework-ready-error/package.json
- test/fixtures/apps/app-start-framework-error/app.js
- test/fixtures/apps/app-start-framework-error/package.json
- test/fixtures/apps/app-start-framework-ready-error/app.js
- test/fixtures/apps/app-start-framework-ready-error/package.json
- test/fixtures/apps/script-start/start-server.js
> feat: catch app/agent boot error to formater FrameworkError

- lib/utils/terminate.js
- test/master.test.js
- test/utils.js
> fix: worker does not get SIGTERM signal from master when close
